   
[✓] Wiki page saved: wiki_pages\page_187448.md
all_links:  ['/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/_TOC_', 'https://learn.microsoft.com/en-us/azure/search/search-security-rbac?tabs=roles-portal-admin%2Croles-portal%2Croles-portal-query%2Ctest-portal%2Ccustom-role-portal#grant-access-to-a-single-index', '/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists-%2D-Auth-&-Networking/AWS-Workstation/Access-To-Azure-Resources', '/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks', '/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster', '/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists-%2D-Auth-&-Networking/AWS-Workstation']
links:  ['/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/_TOC_', '/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists-%252D-Auth-%26-Networking/AWS-Workstation/Access-To-Azure-Resources', '/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks', '/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster', '/Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists-%252D-Auth-%26-Networking/AWS-Workstation']
[+] Matched API-Platform URL: /Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists-%252D-Auth-%26-Networking/AWS-Workstation/Access-To-Azure-Resources
[+] Modified URL: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists---Auth-%26-Networking/AWS-Workstation/Access-To-Azure-Resources
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists---Auth-&-Networking/AWS-Workstation/Access-To-Azure-Resources - status 404
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists-%2D-Auth-&-Networking/AWS-Workstation/Access-To-Azure-Resources - trying direct fetch
[✓] Fallback fetch success: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists---Auth-%26-Networking/AWS-Workstation/Access-To-Azure-Resources
[✓] Saved content to wiki_pages\Access-To-Azure-Resources.md
[+] Matched API-Platform URL: /Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks
[+] Modified URL: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks - status 404
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks - trying direct fetch
[✓] Fallback fetch success: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/Azure-Databricks/Add-Reader-User-to-Databricks
[✓] Saved content to wiki_pages\Add-Reader-User-to-Databricks.md
[+] Matched API-Platform URL: /Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster
[+] Modified URL: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster - status 404
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster - trying direct fetch
[✓] Fallback fetch success: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Specs/AKS/Add-Role-and-Rolebinding-into-AKS-Cluster
[✓] Saved content to wiki_pages\Add-Role-and-Rolebinding-into-AKS-Cluster.md
[+] Matched API-Platform URL: /Audit AIML/_wiki/wikis/Audit-AIML.wiki/pages?path=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists-%252D-Auth-%26-Networking/AWS-Workstation
[+] Modified URL: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists---Auth-%26-Networking/AWS-Workstation
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists---Auth-&-Networking/AWS-Workstation - status 404
[!] REST API failed for path /Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-&-Networking-between-Resources/Developers-and-Data-Scientists-%2D-Auth-&-Networking/AWS-Workstation - trying direct fetch
[✓] Fallback fetch success: https://dev.azure.com/symphonyvsts/Audit%20AIML/_wiki/wikis/Audit-AIML.wiki?wikiVersion=GBwikiMaster&pagePath=/Audit-AIML-Project-Wiki/API-Platform/Cloud-Architecture/Auth-%26-Networking-between-Resources/Developers-and-Data-Scientists---Auth-%26-Networking/AWS-Workstation   
[✓] Saved content to wiki_pages\AWS-Workstation.md
[✓] All URLs saved to: wiki_pages\crawled_urls.txt
